name: Build OnePlus EmberHeart Kernel

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true
    type: string
  ksun_branch_or_hash:
    required: true
    type: string
    default: ""
  susfs_commit_hash_or_branch:
    required: false
    type: string
    default: "dev"
  optimize_level:
    required: false
    type: string
    default: O2
  kernel_uname:
    required: false
    type: string
    default: "EmberHeart"
  manifest:
    required: true
    type: string
    default: OOS15

outputs:
  kernel_version:
    value: ${{ steps.save_metadata.outputs.kernel_version }}
  ksu_version:
    value: ${{ steps.save_metadata.outputs.ksu_version }}
  susfs_version:
    value: ${{ steps.save_metadata.outputs.susfs_version }}
  image_sha256:
    value: ${{ steps.collect_stats.outputs.image_sha256 }}
  warnings:
    value: ${{ steps.collect_stats.outputs.warnings }}

runs:
  using: composite
  steps:
    - name: Parse op_config_json
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"

    - name: Set Manifest
      shell: bash
      run: |
        set -euo pipefail
        echo "OP_MANIFEST=$OP_MANIFEST_${{ inputs.manifest }}" >> "$GITHUB_ENV"

    - name: Validate Inputs
      shell: bash
      run: |
        set -euo pipefail
        if ! [[ "${{ inputs.soc }}" =~ ^[A-Za-z0-9_-]+$ ]]; then exit 1; fi

    - name: Install Minimal Dependencies
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get -o Acquire::Retries=3 update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git curl ca-certificates build-essential clang lld flex bison \
          libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool \
          libxml2-utils rsync unzip dwarves file python3 ccache
        sudo apt-get clean

    - name: Setup Base Environment
      shell: bash
      run: |
        set -euo pipefail
        CONFIG="$OP_MODEL"
        echo "CONFIG=$CONFIG" >> "$GITHUB_ENV"
        REPO="/usr/local/bin/repo"
        if [ ! -x "$REPO" ]; then
          curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO"
          chmod +x "$REPO"
        fi
        echo "REPO=$REPO" >> "$GITHUB_ENV"

    - name: Optimize Global Git for Repo Tool
      shell: bash
      run: |
        set -euo pipefail
        git config --global feature.manyFiles true
        git config --global core.fsmonitor true
        git config --global pack.sparse true

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$CONFIG"
        cd "$CONFIG"
        if [[ "$OP_MANIFEST" == https://* ]]; then
          mkdir -p .repo/manifests
          curl --fail --show-error --location --proto '=https' "$OP_MANIFEST" -o .repo/manifests/temp_manifest.xml
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m temp_manifest.xml --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        else
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b "$OP_BRANCH" -m "$OP_MANIFEST" --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        fi
        
        success=false
        for i in 1 2 3; do
          if "$REPO" sync -c --no-clone-bundle --no-tags --optimized-fetch -j"$(nproc --all)" --fail-fast; then
            success=true
            break
          fi
          sleep 30
        done
        $success || { echo "repo sync failed"; exit 1; }

    # ðŸ”¥ðŸ”¥ FIX 1: UNKE PATCH FOLDER KA KAAM HUM YAHI KAR RAHE HAIN ðŸ”¥ðŸ”¥
    # Fixing the Broken Symlink Issue
    - name: ðŸ”§ FIX BROKEN OOS15 SYMLINKS
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Fix Broken Symlinks"
        SRC_DIR="$GITHUB_WORKSPACE/$CONFIG/kernel_platform/common"
        if [ ! -d "$SRC_DIR" ]; then SRC_DIR="$GITHUB_WORKSPACE/$CONFIG/common"; fi
        TARGET="$SRC_DIR/drivers/base/kernelFwUpdate"
        
        # Unconditional Nuke & Recreate
        rm -rf "$TARGET"
        mkdir -p "$TARGET"
        touch "$TARGET/Kconfig"
        echo "config KERNEL_FW_UPDATE" > "$TARGET/Kconfig"
        echo "    bool 'Firmware update support'" >> "$TARGET/Kconfig"
        echo "    default n" >> "$TARGET/Kconfig"
        echo "âœ… Fixed Symlinks (Manual Patch Applied)"
        echo "::endgroup::"

    - name: Get Kernel Version Info
      shell: bash
      run: |
        set -euo pipefail
        CONFIG_DIR="$GITHUB_WORKSPACE/$CONFIG"
        ARTIFACTS_DIR="$CONFIG_DIR/artifacts"
        mkdir -p "$ARTIFACTS_DIR"
        cd "$CONFIG_DIR/kernel_platform/common"
        VERSION=$(grep '^VERSION *=' Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep '^PATCHLEVEL *=' Makefile | awk '{print $3}')
        echo "KERNEL_VER=$VERSION.$PATCHLEVEL" >> "$GITHUB_ENV"
        echo "SUSFS_KERNEL_BRANCH=gki-$ANDROID_VERSION-$VERSION.$PATCHLEVEL" >> "$GITHUB_ENV"

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.19
      with:
        key: ${{ env.CONFIG }}-kernel-${{ env.KERNEL_VER }}
        max-size: 5G
        create-symlink: true

    - name: Clone AnyKernel3 and Dependencies
      shell: bash
      run: |
        set -euo pipefail
        git clone --depth=1 https://github.com/TheWildJames/AnyKernel3.git -b "gki-2.0"
        git clone --depth=1 https://github.com/TheWildJames/kernel_patches.git
        git clone https://gitlab.com/simonpunk/susfs4ksu.git
        cd susfs4ksu
        git checkout "${{ env.SUSFS_KERNEL_BRANCH }}" || echo "Branch not found, using default"

    - name: Add KernelSU Next & Apply Patches
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform"
        curl --fail --location --proto '=https' -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" | bash -
        cd common
        patch -p1 < ../../../susfs4ksu/kernel_patches/50_add_susfs_in_${{ env.SUSFS_KERNEL_BRANCH }}.patch || true

    # ðŸ”¥ðŸ”¥ FIX 2: DISABLE KGDB (CLANG ERROR FIX) ðŸ”¥ðŸ”¥
    # Ye step wo hai jo 'value 1025' aur 'sp register' wala error hatayega
    - name: Add KSU, SUSFS & DISABLE BROKEN DEBUGGING
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform"
        
        echo "::group::Applying Config Fixes"
        # Standard KSU/SUSFS Configs
        cat >> common/arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_KSU=y
        CONFIG_KSU_SUSFS=y
        CONFIG_KSU_SUSFS_SUS_PATH=y
        EOF
        
        # ðŸ›¡ï¸ THE KILL SWITCH FOR ERRORS ðŸ›¡ï¸
        # KGDB band karne se wo 'sp' aur '1025' wala error gayab ho jayega
        cat >> common/arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_KGDB=n
        CONFIG_KGDB_SERIAL_CONSOLE=n
        CONFIG_KGDB_KDB=n
        CONFIG_HAVE_ARCH_KGDB=n
        CONFIG_CC_WERROR=n
        EOF
        
        echo "âœ… Configs applied: KGDB Disabled, WERROR Disabled."
        echo "::endgroup::"

    - name: Build Kernel
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG"
        echo "Starting Build..."
        ./kernel_platform/build/android/prepare_vendor.sh "$OP_MODEL"
        ./kernel_platform/build/android/build.sh dist -j"$(nproc --all)"

    - name: Copy Files to Artifacts
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/out/dist"
        cp Image "../../../$CONFIG/artifacts/"
        find . -name "*.ko" -exec cp {} "../../../$CONFIG/artifacts/" \;
        
    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CONFIG }}-kernel-and-modules
        path: ${{ env.CONFIG }}/artifacts/*
        
