name: Build OnePlus EmberHeart Kernel

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true
    type: string
  ksun_branch_or_hash:
    required: true
    type: string
    default: ""
  susfs_commit_hash_or_branch:
    required: false
    type: string
    default: "dev"
  optimize_level:
    required: false
    type: string
    default: O2  # Choices: O2 or O3
  kernel_uname:
    required: false
    type: string
    default: "EmberHeart"
  manifest:
    required: true
    type: string
    default: OOS15

outputs:
  kernel_version:
    value: ${{ steps.save_metadata.outputs.kernel_version }}
  ksu_version:
    value: ${{ steps.save_metadata.outputs.ksu_version }}
  susfs_version:
    value: ${{ steps.save_metadata.outputs.susfs_version }}
  image_sha256:
    value: ${{ steps.collect_stats.outputs.image_sha256 }}
  warnings:
    value: ${{ steps.collect_stats.outputs.warnings }}

runs:
  using: composite
  steps:
    - name: Parse op_config_json
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        echo "Parsed config:"
        jq '.' /tmp/config.json

    - name: Set Manifest
      shell: bash
      run: |
        set -euo pipefail
        echo "OP_MANIFEST=$OP_MANIFEST_${{ inputs.manifest }}" >> "$GITHUB_ENV"

    - name: Validate Inputs
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Validate inputs"
        model="$OP_MODEL"
        soc="$OP_SOC"
        branch="$OP_BRANCH"
        manifest="$OP_MANIFEST"
        optimize='${{ inputs.optimize_level }}'

        if ! [[ "$soc" =~ ^[A-Za-z0-9_-]+$ ]]; then
          echo "Input 'soc' contains invalid characters."; exit 1
        fi
        echo "Input validation OK."
        echo "::endgroup::"

    - name: Install Minimal Dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Install deps"
        sudo apt-get -o Acquire::Retries=3 update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git curl ca-certificates build-essential clang lld flex bison \
          libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool \
          libxml2-utils rsync unzip dwarves file python3 ccache
        sudo apt-get clean
        echo "::endgroup::"

    - name: Setup Base Environment
      shell: bash
      run: |
        set -euo pipefail
        CONFIG="$OP_MODEL"
        echo "CONFIG=$CONFIG" >> "$GITHUB_ENV"
        REPO="/usr/local/bin/repo"
        if [ ! -x "$REPO" ]; then
          curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO"
          chmod +x "$REPO"
        fi
        echo "REPO=$REPO" >> "$GITHUB_ENV"

    - name: Optimize Global Git for Repo Tool
      shell: bash
      run: |
        set -euo pipefail
        git config --global feature.manyFiles true
        git config --global core.fsmonitor true
        git config --global pack.sparse true

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        echo "Creating folder for configuration: $CONFIG"
        mkdir -p "$CONFIG"
        cd "$CONFIG"
        echo "Initializing and syncing kernel source..."
        if [[ "$OP_MANIFEST" == https://* ]]; then
          mkdir -p .repo/manifests
          curl --fail --show-error --location --proto '=https' "$OP_MANIFEST" -o .repo/manifests/temp_manifest.xml
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m temp_manifest.xml --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        else
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b "$OP_BRANCH" -m "$OP_MANIFEST" --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        fi
        
        success=false
        for i in 1 2 3; do
          if "$REPO" sync -c --no-clone-bundle --no-tags --optimized-fetch -j"$(nproc --all)" --fail-fast; then
            success=true
            break
          fi
          echo "repo sync attempt $i failed; retrying..."
          sleep 30
        done
        $success || { echo "repo sync failed after 3 attempts"; exit 1; }

    # ðŸ”¥ðŸ”¥ JINN FIX: Fixing Broken Symlinks START ðŸ”¥ðŸ”¥
    - name: ðŸ”§ FIX BROKEN OOS15 SYMLINKS (Jinn Special)
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Fix Broken Symlinks"
        SRC_DIR="$GITHUB_WORKSPACE/$CONFIG/kernel_platform/common"
        if [ ! -d "$SRC_DIR" ]; then SRC_DIR="$GITHUB_WORKSPACE/$CONFIG/common"; fi
        TARGET="$SRC_DIR/drivers/base/kernelFwUpdate"
        
        echo "Checking target: $TARGET"
        if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
            echo "Found broken symlink/folder. Nuking it! ðŸ’¥"
            rm -rf "$TARGET"
            mkdir -p "$TARGET"
            touch "$TARGET/Kconfig"
            echo "config KERNEL_FW_UPDATE" > "$TARGET/Kconfig"
            echo "    bool 'Firmware update support'" >> "$TARGET/Kconfig"
            echo "    default n" >> "$TARGET/Kconfig"
            echo "âœ… Fixed successfully!"
        else
            echo "âš ï¸ Target not found. Skipping fix."
        fi
        echo "::endgroup::"
    # ðŸ”¥ðŸ”¥ JINN FIX END ðŸ”¥ðŸ”¥

    - name: Get Kernel Version Info
      shell: bash
      run: |
        set -euo pipefail
        CONFIG_DIR="$GITHUB_WORKSPACE/$CONFIG"
        ARTIFACTS_DIR="$CONFIG_DIR/artifacts"
        mkdir -p "$ARTIFACTS_DIR"
        cd "$CONFIG_DIR/kernel_platform/common"
        CONFIG_FILES=("build.config.common" "build.config.constants")
        BRANCH_LINE=""
        for f in "${CONFIG_FILES[@]}"; do
          if [ -f "$f" ]; then
            l=$(grep '^[[:space:]]*BRANCH=' "$f" || true)
            if [ -n "$l" ]; then BRANCH_LINE="$l"; break; fi
          fi
        done
        if [ -z "$BRANCH_LINE" ]; then echo "Error: No BRANCH= found"; exit 1; fi
        BRANCH_VALUE="${BRANCH_LINE#*=}"
        ANDROID_VERSION="${BRANCH_VALUE%-*}"
        VERSION=$(grep '^VERSION *=' Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep '^PATCHLEVEL *=' Makefile | awk '{print $3}')
        SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | awk '{print $3}')
        FULL_VERSION="$VERSION.$PATCHLEVEL.$SUBLEVEL"
        cd "$ARTIFACTS_DIR"
        echo "$ANDROID_VERSION-$FULL_VERSION" > "${OP_MODEL}.txt"
        echo "ANDROID_VER=$ANDROID_VERSION" >> "$GITHUB_ENV"
        echo "KERNEL_VER=$VERSION.$PATCHLEVEL" >> "$GITHUB_ENV"
        echo "KERNEL_FULL_VER=$ANDROID_VERSION-$FULL_VERSION" >> "$GITHUB_ENV"
        echo "SUSFS_KERNEL_BRANCH=gki-$ANDROID_VERSION-$VERSION.$PATCHLEVEL" >> "$GITHUB_ENV"

    - name: Set Build Identity
      shell: bash
      run: |
        set -euo pipefail
        echo "KBUILD_BUILD_USER=EmberHeart" >> "$GITHUB_ENV"
        echo "KBUILD_BUILD_HOST=OnePlus" >> "$GITHUB_ENV"

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.19
      with:
        key: ${{ env.CONFIG }}-kernel-${{ env.KERNEL_FULL_VER }}
        max-size: 5G
        create-symlink: true

    - name: Clone AnyKernel3 and Other Dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "Cloning AnyKernel3..."
        ANYKERNEL_BRANCH="gki-2.0"
        if [[ -z "${{ inputs.susfs_commit_hash_or_branch }}" ]]; then
          SUSFS_BRANCH="${{ env.SUSFS_KERNEL_BRANCH }}"
        else
          SUSFS_BRANCH="${{ inputs.susfs_commit_hash_or_branch }}"
        fi
        git clone --depth=1 https://github.com/TheWildJames/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
        git clone --depth=1 https://github.com/TheWildJames/kernel_patches.git
        git clone https://gitlab.com/simonpunk/susfs4ksu.git
        cd susfs4ksu
        git checkout "$SUSFS_BRANCH" || echo "Warning: Branch not found"

    - name: Add KernelSU Next
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform"
        curl --fail --location --proto '=https' -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/dev/kernel/setup.sh" | bash -
        cd common
        patch -p1 < ../../../susfs4ksu/kernel_patches/50_add_susfs_in_${{ env.SUSFS_KERNEL_BRANCH }}.patch || true

    - name: Add BBG
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform"
        wget -O- https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh | bash -s fix_blkdev_rename || echo "BBG warning"
        echo "CONFIG_BBG=y" >> common/arch/arm64/configs/gki_defconfig

    - name: Add KernelSU-Next and SUSFS Configuration Settings
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform"
        cat >> common/arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_KSU=y
        CONFIG_KSU_KPROBES_HOOK=n
        CONFIG_KSU_SUSFS=y
        CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
        CONFIG_KSU_SUSFS_SUS_PATH=y
        CONFIG_KSU_SUSFS_SUS_MOUNT=y
        CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
        CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
        CONFIG_KSU_SUSFS_SUS_SU=y
        CONFIG_KSU_SUSFS_TRY_UMOUNT=y
        CONFIG_KSU_SUSFS_SPOOF_UNAME=y
        CONFIG_KSU_SUSFS_ENABLE_LOG=y
        CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
        CONFIG_KSU_SUSFS_SUS_KSTAT=y
        CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y
        EOF

    - name: Build Kernel
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG"
        ./kernel_platform/build/android/prepare_vendor.sh "$OP_MODEL"
        ./kernel_platform/build/android/build.sh dist -j"$(nproc --all)"

    - name: Copy Files to Artifacts
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/out/dist"
        cp Image "../../../$CONFIG/artifacts/"
        find . -name "*.ko" -exec cp {} "../../../$CONFIG/artifacts/" \;
        
    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CONFIG }}-kernel-and-modules
        path: ${{ env.CONFIG }}/artifacts/*
        
